import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Booking, LedgerEntry, FoodOrder, RoomStatus } from './firestoreService';

// Ensure autoTable is correctly added to jsPDF prototype
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(jsPDF as any).autoTable = autoTable;

interface AuditReportData {
    businessDate: Date;
    stayingOver: Booking[];
    arrivalsTomorrow: Booking[];
    departuresTomorrow: Booking[];
    checkedOutToday: Booking[];
    generatedBy: string;
    // New Data Sections
    financeData?: {
        ledgerEntries: LedgerEntry[];
        totalRevenue: number;
    };
    fbData?: {
        orders: FoodOrder[];
    };
    housekeepingData?: {
        rooms: any[]; // casting to any for now to avoid specific interface issues if RoomStatus is complex
    };
}

export const generateNightAuditPDF = (data: AuditReportData): Buffer => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // --- Header ---
    doc.setFillColor(26, 26, 26); // Dark background
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Sultan Palace", 14, 15);

    doc.setFontSize(16);
    doc.setTextColor(200, 200, 200);
    doc.text("Night Audit Report", pageWidth - 14, 15, { align: 'right' });

    doc.setFontSize(10);
    doc.text(`Business Date: ${data.businessDate.toLocaleDateString()}`, pageWidth - 14, 25, { align: 'right' });
    doc.text(`Generated By: ${data.generatedBy}`, pageWidth - 14, 30, { align: 'right' });

    let finalY = 45;

    // --- Helper: Check Page Break ---
    const checkPageBreak = (heightParams: number = 20) => {
        if (finalY + heightParams > pageHeight - 20) {
            doc.addPage();
            finalY = 20;
        }
    };

    // --- 1. Manager's Flash Report (Executive Summary) ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Manager's Flash Report", 14, finalY);
    finalY += 10;

    const totalRoomRev = data.financeData?.totalRevenue || 0;
    const fbRev = data.fbData?.orders?.reduce((sum, o) => sum + (o.totalAmount || 0), 0) || 0;
    const occupiedRooms = data.stayingOver.length;
    // Simple ADR calc
    const adr = occupiedRooms > 0 ? (totalRoomRev / occupiedRooms) : 0;

    const summaryData = [
        ['Total Revenue (Today)', `$ ${(totalRoomRev + fbRev).toFixed(2)}`],
        ['Room Revenue', `$ ${totalRoomRev.toFixed(2)}`],
        ['F&B Revenue', `$ ${fbRev.toFixed(2)}`],
        ['Occupied Rooms', `${occupiedRooms}`],
        // ['Occupancy %', `${((occupiedRooms / 20) * 100).toFixed(1)}%`], // Hardcoded 20 rooms assumption removed
        ['ADR (Avg Daily Rate)', `$ ${adr.toFixed(2)}`]
    ];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).autoTable({
        startY: finalY,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [50, 50, 50], textColor: 255, fontStyle: 'bold' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 }, 1: { halign: 'right' } },
        margin: { left: 14, right: 100 }, // Compact table
        tableWidth: 100
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    finalY = (doc as any).lastAutoTable.finalY + 15;


    // --- 2. Finance Report (Detailed Ledger) ---
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.text("Finance Report (Today's Transactions)", 14, finalY);
    finalY += 5;

    const ledgerData = data.financeData?.ledgerEntries.map(e => [
        // e.createdAt?.toLocaleTimeString() || '-', // formatting issue if Date not parsed
        new Date(e.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        e.description,
        e.category.toUpperCase(),
        e.paymentMethod?.toUpperCase() || '-',
        e.entryType === 'income' ? `+${e.amount.toFixed(2)}` : `-${e.amount.toFixed(2)}`
    ]) || [];

    if (ledgerData.length > 0) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).autoTable({
            startY: finalY,
            head: [['Time', 'Description', 'Category', 'Method', 'Amount']],
            body: ledgerData,
            theme: 'striped',
            headStyles: { fillColor: [41, 128, 185] },
            columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } },
            styles: { fontSize: 8 }
        });
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        finalY = (doc as any).lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.text("No transactions recorded today.", 14, finalY + 5);
        finalY += 15;
    }


    // --- 3. F&B Report (Kitchen Orders) ---
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("F&B Report (Kitchen & Bar)", 14, finalY);
    finalY += 5;

    const fbOrders = data.fbData?.orders.map(o => [
        o.orderNumber,
        o.roomNumber || o.deliveryLocation,
        o.status.toUpperCase(),
        `$ ${o.totalAmount.toFixed(2)}`
    ]) || [];

    if (fbOrders.length > 0) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).autoTable({
            startY: finalY,
            head: [['Order #', 'Location', 'Status', 'Total']],
            body: fbOrders,
            theme: 'striped',
            headStyles: { fillColor: [243, 156, 18] }, // Orange/Food color
            columnStyles: { 3: { halign: 'right' } }
        });
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        finalY = (doc as any).lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.text("No F&B orders today.", 14, finalY + 5);
        finalY += 15;
    }


    // --- 4. Housekeeping Status ---
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Housekeeping Status", 14, finalY);
    finalY += 5;

    // Count statuses
    let cleanCount = 0;
    let dirtyCount = 0;
    let maintCount = 0;
    const dirtyRoomsList: string[] = [];

    data.housekeepingData?.rooms.forEach(r => {
        const s = r.housekeepingStatus || 'clean'; // Default to clean if missing
        if (s === 'clean') cleanCount++;
        if (s === 'dirty' || s === 'needs_inspection') {
            dirtyCount++;
            dirtyRoomsList.push(r.name || r.roomName || 'Unknown');
        }
        if (s === 'maintenance') maintCount++;
    });

    const hkData = [
        ['Clean / Ready', cleanCount],
        ['Dirty / Occupied / Inspection', dirtyCount],
        ['Under Maintenance', maintCount]
    ];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).autoTable({
        startY: finalY,
        head: [['Status', 'Count']],
        body: hkData,
        theme: 'plain', // Simple table
        headStyles: { fillColor: [142, 68, 173] }, // Purple
        tableWidth: 100,
        margin: { left: 14 }
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    finalY = (doc as any).lastAutoTable.finalY + 10;

    // List dirty rooms if any
    if (dirtyRoomsList.length > 0) {
        doc.setFontSize(10);
        doc.text(`Dirty Rooms: ${dirtyRoomsList.join(', ')}`, 14, finalY);
        finalY += 15;
    } else {
        finalY += 5;
    }


    // --- 5. Guest Reports (Existing Logic) ---

    // Helper used for guest tables
    const drawGuestTable = (title: string, bookings: Booking[], themeColor: string = 'orange') => {
        if (bookings.length === 0) return;
        checkPageBreak(60);

        doc.setFontSize(12);
        doc.setTextColor(50, 50, 50);
        doc.text(`${title} (${bookings.length})`, 14, finalY);
        finalY += 5;

        let headerColor = [22, 163, 74];
        if (themeColor === 'orange') headerColor = [234, 88, 12];
        if (themeColor === 'red') headerColor = [220, 38, 38];
        if (themeColor === 'blue') headerColor = [37, 99, 235];

        const tableData = bookings.map(b => [
            b.bookingId.substring(0, 8),
            `${b.guestDetails.firstName} ${b.guestDetails.lastName}`,
            b.rooms.map(r => r.allocatedRoomType || r.type).join(', '),
            `${b.guests.adults}/${b.guests.children}`,
            b.rooms[0]?.mealPlan || '-',
            // Safe date parsing
            b.checkIn ? new Date(b.checkIn).toLocaleDateString() : '-',
            b.checkOut ? new Date(b.checkOut).toLocaleDateString() : '-',
            (b.totalAmount - (b.paidAmount || 0)).toFixed(2)
        ]);

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).autoTable({
            startY: finalY,
            head: [['Res No', 'Guest', 'Room', 'Pax', 'Meal', 'In', 'Out', 'Bal']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: headerColor, textColor: 255 },
            styles: { fontSize: 8 },
            columnStyles: { 7: { halign: 'right' } }
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        finalY = (doc as any).lastAutoTable.finalY + 15;
    };

    drawGuestTable("Staying Over Guests", data.stayingOver, 'orange');
    drawGuestTable("Arrivals Tomorrow", data.arrivalsTomorrow, 'green');
    drawGuestTable("Departures Tomorrow", data.departuresTomorrow, 'red');
    drawGuestTable("Today's Check-Outs", data.checkedOutToday, 'blue');


    // --- Footer ---
    checkPageBreak(20);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text("--- End of Confidential Night Audit Report ---", pageWidth / 2, finalY + 10, { align: 'center' });

    return Buffer.from(doc.output('arraybuffer'));
};
