import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Booking,
  LedgerEntry,
  FoodOrder,
} from "./firestoreService";
import type { POSData } from "@/app/actions/nightAuditActions";

// ─────────────────────────────────────────────────────────────────────────────
// DATA SHAPE
// ─────────────────────────────────────────────────────────────────────────────

interface AuditReportData {
  businessDate: Date;
  stayingOver: Booking[];
  arrivalsTomorrow: Booking[];
  departuresTomorrow: Booking[];
  checkedOutToday: Booking[];
  generatedBy: string;
  financeData?: {
    ledgerEntries: LedgerEntry[];
    totalRevenue: number;
  };
  /** Rich POS section — replaces the old fbData.orders basic table */
  posData?: POSData;
  housekeepingData?: {
    rooms: any[];
  };
  // Legacy fallback (kept so callers that haven't migrated still compile)
  fbData?: { orders: FoodOrder[] };
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

const $ = (n: number) => `$ ${n.toFixed(2)}`;

// ─────────────────────────────────────────────────────────────────────────────
// MAIN EXPORT
// ─────────────────────────────────────────────────────────────────────────────

export const generateNightAuditPDF = (data: AuditReportData): Buffer => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // ── Header ─────────────────────────────────────────────────────────────────
  doc.setFillColor(26, 26, 26);
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("Sultan Palace", 14, 15);

  doc.setFontSize(16);
  doc.setTextColor(200, 200, 200);
  doc.text("Night Audit Report", pageWidth - 14, 15, { align: "right" });

  doc.setFontSize(10);
  doc.text(`Business Date: ${data.businessDate.toLocaleDateString()}`, pageWidth - 14, 25, { align: "right" });
  doc.text(`Generated By: ${data.generatedBy}`, pageWidth - 14, 30, { align: "right" });

  let finalY = 45;

  // ── Page-break helper ──────────────────────────────────────────────────────
  const checkPageBreak = (height = 20) => {
    if (finalY + height > pageHeight - 20) {
      doc.addPage();
      finalY = 20;
    }
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const lastY = () => (doc as any).lastAutoTable.finalY;

  const sectionTitle = (text: string, color: [number, number, number] = [26, 26, 26]) => {
    checkPageBreak(20);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(text, 14, finalY);
    finalY += 5;
  };

  // ── 1. Manager's Flash Report ──────────────────────────────────────────────
  doc.setTextColor(0, 0, 0);
  sectionTitle("Manager's Flash Report");

  const pos = data.posData;
  const totalRoomRev = data.financeData?.totalRevenue || 0;
  const fbRev = pos?.posSales ?? (data.fbData?.orders?.reduce((s, o) => s + (o.totalAmount || 0), 0) ?? 0);
  const occupiedRooms = data.stayingOver.length;
  const adr = occupiedRooms > 0 ? totalRoomRev / occupiedRooms : 0;

  const flashRows: [string, string][] = [
    ["Total Revenue (Today)", $(totalRoomRev + fbRev)],
    ["Room Revenue", $(totalRoomRev)],
    ["F&B / POS Revenue", $(fbRev)],
    ["Occupied Rooms", `${occupiedRooms}`],
    ["ADR (Avg Daily Rate)", $(adr)],
  ];

  if (pos) {
    flashRows.push(
      ["Food Cost (COGS)", $(pos.foodCost)],
      ["Order Profit", $(pos.orderProfit)],
      ["Food Cost %", `${pos.foodCostPercentage.toFixed(1)}%`],
    );
  }

  autoTable(doc, {
    startY: finalY,
    head: [["Metric", "Value"]],
    body: flashRows,
    theme: "grid",
    headStyles: { fillColor: [50, 50, 50], textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 80 },
      1: { halign: "right" },
    },
    margin: { left: 14, right: 100 },
    tableWidth: 100,
  });
  finalY = lastY() + 15;

  // ── 2. Finance Report ──────────────────────────────────────────────────────
  sectionTitle("Finance Report (Today's Transactions)", [41, 128, 185]);

  const ledgerData = data.financeData?.ledgerEntries.map(e => [
    new Date(e.date).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    e.description,
    e.category.toUpperCase(),
    e.paymentMethod?.toUpperCase() || "-",
    e.entryType === "income" ? `+${e.amount.toFixed(2)}` : `-${e.amount.toFixed(2)}`,
  ]) || [];

  if (ledgerData.length > 0) {
    autoTable(doc, {
      startY: finalY,
      head: [["Time", "Description", "Category", "Method", "Amount"]],
      body: ledgerData,
      theme: "striped",
      headStyles: { fillColor: [41, 128, 185] },
      columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
      styles: { fontSize: 8 },
    });
    finalY = lastY() + 15;
  } else {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 100, 100);
    doc.text("No transactions recorded today.", 14, finalY + 5);
    finalY += 15;
  }

  // ── 3. POS Summary ─────────────────────────────────────────────────────────
  sectionTitle("POS Summary (F&B & Bar)", [180, 85, 0]);

  if (pos && pos.totalOrders > 0) {
    autoTable(doc, {
      startY: finalY,
      head: [["Item", "Amount"]],
      body: [
        ["POS Sales (Subtotal)", $(pos.posSales)],
        ["Tax", $(pos.tax)],
        ["Discount", `-${$(pos.discount)}`],
        ["Total", $(pos.total)],
        ["Payments Received", $(pos.payments)],
        ["Outstanding", $(Math.max(0, pos.total - pos.payments))],
      ],
      theme: "grid",
      headStyles: { fillColor: [243, 156, 18], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 90 },
        1: { halign: "right" },
      },
      margin: { left: 14, right: 80 },
      tableWidth: 120,
    });
    finalY = lastY() + 10;

    // ── 3a. Payment Breakdown ────────────────────────────────────────────────
    checkPageBreak(40);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("  Payment Breakdown", 14, finalY);
    finalY += 5;

    const breakdownRows = Object.entries(pos.paymentBreakdown).map(([method, amount]) => [
      method.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase()),
      $(amount),
    ]);

    if (breakdownRows.length > 0) {
      autoTable(doc, {
        startY: finalY,
        head: [["Payment Method", "Amount"]],
        body: breakdownRows,
        theme: "plain",
        headStyles: { fillColor: [248, 196, 113], textColor: 0 },
        columnStyles: {
          0: { cellWidth: 90 },
          1: { halign: "right" },
        },
        margin: { left: 14, right: 80 },
        tableWidth: 120,
        styles: { fontSize: 9 },
      });
      finalY = lastY() + 12;
    }

    // ── 3b. Total Orders (summary line) ─────────────────────────────────────
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text(`Total orders processed: ${pos.totalOrders}`, 14, finalY);
    finalY += 12;

  } else {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 100, 100);
    doc.text("No POS orders recorded today.", 14, finalY + 5);
    finalY += 15;
  }

  // ── 4. Food Cost & Profit ──────────────────────────────────────────────────
  sectionTitle("Food Cost & Profit Analysis", [39, 174, 96]);

  if (pos) {
    autoTable(doc, {
      startY: finalY,
      head: [["Metric", "Value"]],
      body: [
        ["POS Revenue (Subtotal)", $(pos.orderRevenue)],
        ["Cost of Goods Sold", $(pos.foodCost)],
        ["Gross Profit", $(pos.orderProfit)],
        ["Food Cost Percentage", `${pos.foodCostPercentage.toFixed(1)}%`],
      ],
      theme: "grid",
      headStyles: { fillColor: [39, 174, 96], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 90 },
        1: { halign: "right" },
      },
      margin: { left: 14, right: 80 },
      tableWidth: 120,
    });
    finalY = lastY() + 15;
  }

  // ── 5. Top 5 Selling Dishes ────────────────────────────────────────────────
  if (pos && pos.topDishes.length > 0) {
    sectionTitle("Top 5 Selling Dishes", [142, 68, 173]);
    autoTable(doc, {
      startY: finalY,
      head: [["Dish", "Qty Sold", "Revenue"]],
      body: pos.topDishes.map((d, i) => [
        `${i + 1}. ${d.name}`,
        `${d.qty}`,
        $(d.revenue),
      ]),
      theme: "striped",
      headStyles: { fillColor: [142, 68, 173], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        1: { halign: "center" },
        2: { halign: "right" },
      },
      styles: { fontSize: 9 },
    });
    finalY = lastY() + 15;
  }

  // ── 6. Ingredient Consumption ──────────────────────────────────────────────
  if (pos && pos.mostConsumedIngredient.length > 0) {
    sectionTitle("Top Ingredient Consumption", [41, 128, 185]);
    autoTable(doc, {
      startY: finalY,
      head: [["Ingredient", "Qty Used", "Unit"]],
      body: pos.mostConsumedIngredient.map(ing => [
        ing.name,
        ing.qty.toFixed(3),
        ing.unit,
      ]),
      theme: "striped",
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 9 },
    });
    finalY = lastY() + 15;

    // Highest-cost & highest-revenue dish callouts
    if (pos.highestCostDish || pos.highestRevenueDish) {
      checkPageBreak(20);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(50, 50, 50);
      if (pos.highestCostDish) {
        doc.text(`Highest Cost Dish: ${pos.highestCostDish.name} — ${$(pos.highestCostDish.cost)}`, 14, finalY);
        finalY += 7;
      }
      if (pos.highestRevenueDish) {
        doc.text(`Highest Revenue Dish: ${pos.highestRevenueDish.name} — ${$(pos.highestRevenueDish.revenue)}`, 14, finalY);
        finalY += 12;
      }
    }
  }

  // ── 7. Housekeeping Status ─────────────────────────────────────────────────
  sectionTitle("Housekeeping Status", [100, 100, 100]);

  let cleanCount = 0, dirtyCount = 0, maintCount = 0;
  const dirtyRoomsList: string[] = [];

  data.housekeepingData?.rooms.forEach(r => {
    const s = r.housekeepingStatus || "clean";
    if (s === "clean") cleanCount++;
    if (s === "dirty" || s === "needs_inspection") {
      dirtyCount++;
      dirtyRoomsList.push(r.name || r.roomName || "Unknown");
    }
    if (s === "maintenance") maintCount++;
  });

  autoTable(doc, {
    startY: finalY,
    head: [["Status", "Count"]],
    body: [
      ["Clean / Ready", cleanCount],
      ["Dirty / Inspection", dirtyCount],
      ["Under Maintenance", maintCount],
    ],
    theme: "plain",
    headStyles: { fillColor: [100, 100, 100], textColor: 255 },
    tableWidth: 100,
    margin: { left: 14 },
  });
  finalY = lastY() + 10;

  if (dirtyRoomsList.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`Dirty Rooms: ${dirtyRoomsList.join(", ")}`, 14, finalY);
    finalY += 15;
  } else {
    finalY += 5;
  }

  // ── 8. Guest Reports ───────────────────────────────────────────────────────
  const drawGuestTable = (title: string, bookings: Booking[], themeColor: string = "orange") => {
    if (bookings.length === 0) return;
    checkPageBreak(60);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text(`${title} (${bookings.length})`, 14, finalY);
    finalY += 5;

    let headerColor: [number, number, number] = [22, 163, 74];
    if (themeColor === "orange") headerColor = [234, 88, 12];
    if (themeColor === "red") headerColor = [220, 38, 38];
    if (themeColor === "blue") headerColor = [37, 99, 235];

    const tableData = bookings.map(b => [
      b.bookingId.substring(0, 8),
      `${b.guestDetails.firstName} ${b.guestDetails.lastName}`,
      b.rooms.map(r => r.allocatedRoomType || r.type).join(", "),
      `${b.guests.adults}/${b.guests.children}`,
      b.rooms[0]?.mealPlan || "-",
      b.checkIn ? new Date(b.checkIn).toLocaleDateString() : "-",
      b.checkOut ? new Date(b.checkOut).toLocaleDateString() : "-",
      (b.totalAmount - (b.paidAmount || 0)).toFixed(2),
    ]);

    autoTable(doc, {
      startY: finalY,
      head: [["Res No", "Guest", "Room", "Pax", "Meal", "In", "Out", "Bal"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: headerColor, textColor: 255 },
      styles: { fontSize: 8 },
      columnStyles: { 7: { halign: "right" } },
    });

    finalY = lastY() + 15;
  };

  drawGuestTable("Staying Over Guests", data.stayingOver, "orange");
  drawGuestTable("Arrivals Tomorrow", data.arrivalsTomorrow, "green");
  drawGuestTable("Departures Tomorrow", data.departuresTomorrow, "red");
  drawGuestTable("Today's Check-Outs", data.checkedOutToday, "blue");

  // ── Footer ─────────────────────────────────────────────────────────────────
  checkPageBreak(20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(
    "--- End of Confidential Night Audit Report ---",
    pageWidth / 2,
    finalY + 10,
    { align: "center" },
  );

  return Buffer.from(doc.output("arraybuffer"));
};
