/**
 * Menu Items Seeder - Part 2 (Items 25-57)
 * Indian Veg + Non-Veg + Pizza + Burgers + Salads
 * Run: npx tsx scripts/seedMenuItems-part2.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

const menuItems = [
  // INDIAN VEGETARIAN (7 items)
  {
    id: "mi_indian_veg_paneer_masala",
    name: "Paneer masala",
    description:
      "Tomato sauce, cashew nuts sauce, chop masala, cottage cheese.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "nuts"],
    isAvailable: true,
    isPopular: false,
    sku: "PNM008",
    images: [],
  },
  {
    id: "mi_indian_veg_kadai_paneer",
    name: "Kadai paneer",
    description:
      "Cottage cheese, coriander seeds, cumin seeds, bell pepper, chop masala, onion & tomato sauce.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "KDP008",
    images: [],
  },
  {
    id: "mi_indian_veg_paneer_tikka_masala",
    name: "Paneer tikka masala",
    description:
      "Tomato sauce, cashew nuts sauce, chop masala, cottage cheese, bell pepper & onion.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 9,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "nuts"],
    isAvailable: true,
    isPopular: false,
    sku: "PTM009",
    images: [],
  },
  {
    id: "mi_indian_veg_mixed_vegetables",
    name: "Mixed vegetables",
    description: "Green beans, carrot, broccoli, cauliflower, & zucchini.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MXV008",
    images: [],
  },
  {
    id: "mi_indian_veg_bhindi_masala",
    name: "Bhindi masala",
    description: "Lady finger mixed with masala sauce.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "BHM007",
    images: [],
  },
  {
    id: "mi_indian_veg_dal_tadka",
    name: "Dal tadka",
    description: "Yellow & red lentil, onion tomato, garlic & green chilli.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "DLT007",
    images: [],
  },
  {
    id: "mi_indian_veg_dal_makani",
    name: "Dal Makani",
    description:
      "Black & yellow lentil, red beans, garlic, tomato pesto, cream & butter.",
    categoryId: "cat_indian_vegetarian",
    kitchenSection: "indian",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "DLM007",
    images: [],
  },

  // INDIAN NON-VEGETARIAN (8 items)
  {
    id: "mi_indian_nonveg_kadai_chicken",
    name: "Kadai Chicken",
    description: "Bell pepper, chop masala, chicken, gravy sauce.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "KDC012",
    images: [],
  },
  {
    id: "mi_indian_nonveg_punjabi_chicken",
    name: "Punjabi Chicken",
    description: "Chop masala, tomato gravy, white gravy, chicken.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "PJC015",
    images: [],
  },
  {
    id: "mi_indian_nonveg_chicken_curry",
    name: "Chicken curry",
    description: "Chicken, chop masala, tomato gravy, onion gravy.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "CHC015",
    images: [],
  },
  {
    id: "mi_indian_nonveg_mutton_masala",
    name: "Mutton masala",
    description: "Onion, ginger garlic paste yoghurt, tomato gravy.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "MTM015",
    images: [],
  },
  {
    id: "mi_indian_nonveg_mutton_rogan_josh",
    name: "Mutton Rogan josh",
    description:
      "Onion, ginger garlic paste, white paste, yoghurt, tomato paste.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "MRJ015",
    images: [],
  },
  {
    id: "mi_indian_nonveg_chilli_chicken",
    name: "Chilli Chicken",
    description: "Chicken, green pepper, green chilli, onion, red pepper.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "CLC012",
    images: [],
  },
  {
    id: "mi_indian_nonveg_chicken_biryani",
    name: "Chicken Biryani",
    description: "Chicken, tomato sauce, white sauce, yoghurt, rice.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "CBR015",
    images: [],
  },
  {
    id: "mi_indian_nonveg_chicken_fried_rice",
    name: "Chicken Fried rice",
    description: "Chicken, rice, yellow & green pepper, onion, carrot.",
    categoryId: "cat_indian_non_vegetarian",
    kitchenSection: "indian",
    basePrice: 13,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "ICF013",
    images: [],
  },

  // PIZZA (8 items)
  {
    id: "mi_pizza_focaccia",
    name: "Focaccia pizza",
    description: "Olive oil & oregano.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "FCP005",
    images: [],
  },
  {
    id: "mi_pizza_margarita",
    name: "Margarita pizza",
    description: "Tomato & cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true, nightItemId: "mi_night_margarita_pizza" },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MZP010",
    images: [],
  },
  {
    id: "mi_pizza_chicken",
    name: "Chicken pizza",
    description: "Tomato, chicken and cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CKP012",
    images: [],
  },
  {
    id: "mi_pizza_cheese",
    name: "Cheese pizza",
    description: "Tomato, cheddar cheese & mozzarella cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CHP015",
    images: [],
  },
  {
    id: "mi_pizza_hawaiian",
    name: "Hawaiian pizza",
    description: "Tomato, chicken, pineapple & cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true, nightItemId: "mi_night_hawaiian_pizza" },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "HWP012",
    images: [],
  },
  {
    id: "mi_pizza_vegetable",
    name: "Vegetable pizza",
    description: "Tomato carrot, broccoli, bell pepper, zucchini & cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 11,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "VGP011",
    images: [],
  },
  {
    id: "mi_pizza_seafood",
    name: "Seafood pizza",
    description: "Tomato, fish, prawns, octopus, calamari.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "fish", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "SFP015",
    images: [],
  },
  {
    id: "mi_pizza_sultan_special",
    name: "Sultan special pizza",
    description: "Eggs, mushroom, chickpeas, bell pepper, mutton cheese.",
    categoryId: "cat_pizza",
    kitchenSection: "continental",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "eggs"],
    isAvailable: true,
    isPopular: true,
    sku: "SSP015",
    images: [],
  },

  // BURGERS (3 items)
  {
    id: "mi_burger_chicken",
    name: "Chicken burger",
    description: "Lettuce, tomato, cucumber, onion, chopped chicken & cheese.",
    categoryId: "cat_burgers",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "BKC012",
    images: [],
  },
  {
    id: "mi_burger_vegetables",
    name: "Vegetables burger",
    description:
      "Lettuce, tomato, onion, carrot, zucchini, bell pepper & cheese.",
    categoryId: "cat_burgers",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "BKV010",
    images: [],
  },
  {
    id: "mi_burger_cheese",
    name: "Cheese burger",
    description: "Lettuce, tomato, onion, cucumber & cheddar cheese.",
    categoryId: "cat_burgers",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "BKH010",
    images: [],
  },

  // SALADS (7 items)
  {
    id: "mi_salad_seafood",
    name: "Seafood salad",
    description:
      "Tomato, onion, cucumber, lettuce, sauteed fish, octopus, prawns.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "SLD007",
    images: [],
  },
  {
    id: "mi_salad_greek",
    name: "Greek salad",
    description: "Onion, lettuce, cucumber, tomato, olives, feta cheese.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "GRS006",
    images: [],
  },
  {
    id: "mi_salad_chickpeas",
    name: "Chickpeas salad",
    description: "Chickpeas, carrot, onion, tomato, baby corn, bell pepper.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "CPS006",
    images: [],
  },
  {
    id: "mi_salad_chicken_caesar",
    name: "Chicken Caesar salad",
    description: "Lettuce, chicken, crouton, parmesan cheese.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "CCS006",
    images: [],
  },
  {
    id: "mi_salad_prawns_avocado",
    name: "Prawns and avocado salad",
    description: "Prawns, avocado, apple, tomato, lettuce, cucumber, onion.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "PAS008",
    images: [],
  },
  {
    id: "mi_salad_mixed",
    name: "Mixed salad",
    description: "Onion, tomato, lettuce, carrot, cucumber, bell pepper.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MXS006",
    images: [],
  },
  {
    id: "mi_salad_hot_chicken",
    name: "Hot chicken salad",
    description: "Chicken, tomato, onion, bell pepper, papaya.",
    categoryId: "cat_salad",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "HCS007",
    images: [],
  },
];

async function seed() {
  console.log("🚀 Seeding Part 2 (33 items)...\n");
  const now = new Date();
  const batch = db.batch();
  for (const item of menuItems) {
    const { id, ...data } = item;
    batch.set(db.collection(COLLECTION).doc(id), {
      ...data,
      createdAt: now,
      updatedAt: now,
    });
    console.log(`📝 ${item.name}`);
  }
  await batch.commit();
  console.log(`\n✅ Part 2 complete: ${menuItems.length} items seeded!`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
