/**
 * Beverage Menu Items Seeder - Part 3 (Items 61-97)
 * Vodka (1) + Gin (4) + Tequila (2) + Whiskey (7) + Rum (4) +
 * Liqueurs (10) + Boosters (3) + Milkshakes (5) + Smokers (1)
 * Run: npx tsx scripts/seedBeverageItems-part3.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

const beverageItems = [
  // ===========================================================================
  // VODKA (1 item continued) - cat_vodka - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_vod004",
    name: "Belvedere",
    description: "Premium Polish vodka with smooth character",
    images: [],
    categoryId: "cat_vodka",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_vod004_shot",
        name: "Shot",
        price: 5,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_vod004_bottle",
        name: "Bottle",
        price: 140,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "VOD004",
  },

  // ===========================================================================
  // GIN (4 items continued) - cat_gin - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_gin004",
    name: "Gordon's",
    description: "Classic London dry gin",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin004_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin004_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "GIN004",
  },
  {
    id: "item_gin005",
    name: "Konyagi",
    description: "Tanzanian gin spirit",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin005_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin005_bottle",
        name: "Bottle",
        price: 50,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "GIN005",
  },
  {
    id: "item_gin006",
    name: "Safari",
    description: "Local gin with distinctive flavor",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin006_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin006_bottle",
        name: "Bottle",
        price: 60,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "GIN006",
  },
  {
    id: "item_gin007",
    name: "King Robert",
    description: "Premium gin with rich flavor profile",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin007_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin007_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "GIN007",
  },

  // ===========================================================================
  // TEQUILA (2 items continued) - cat_tequila - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_teq004",
    name: "El Charro Silver",
    description: "Mexican silver tequila with authentic taste",
    images: [],
    categoryId: "cat_tequila",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_teq004_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_teq004_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "TEQ004",
  },
  {
    id: "item_teq005",
    name: "Camino Gold",
    description: "Golden tequila with smooth finish",
    images: [],
    categoryId: "cat_tequila",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_teq005_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_teq005_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "TEQ005",
  },

  // ===========================================================================
  // WHISKEY (7 items) - cat_whiskey - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_whi001",
    name: "Macallan",
    description: "Premium Scotch whisky with rich sherry notes",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi001_shot",
        name: "Shot",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi001_bottle",
        name: "Bottle",
        price: 160,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI001",
  },
  {
    id: "item_whi002",
    name: "Glenfiddich",
    description: "Single malt Scotch with smooth, fruity character",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi002_shot",
        name: "Shot",
        price: 7,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi002_bottle",
        name: "Bottle",
        price: 143,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI002",
  },
  {
    id: "item_whi003",
    name: "Chivas",
    description: "Blended Scotch whisky with smooth finish",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi003_shot",
        name: "Shot",
        price: 5,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi003_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI003",
  },
  {
    id: "item_whi004",
    name: "Johnnie Walker Red",
    description: "Bold blended Scotch whisky",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi004_shot",
        name: "Shot",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi004_bottle",
        name: "Bottle",
        price: 140,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI004",
  },
  {
    id: "item_whi005",
    name: "Johnnie Walker Black",
    description: "Premium blended Scotch with rich complexity",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi005_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi005_bottle",
        name: "Bottle",
        price: 90,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI005",
  },
  {
    id: "item_whi006",
    name: "Jameson",
    description: "Irish whiskey with smooth, triple-distilled character",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi006_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi006_bottle",
        name: "Bottle",
        price: 90,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI006",
  },
  {
    id: "item_whi007",
    name: "Jack Daniel's",
    description: "Tennessee whiskey with smooth, charcoal-mellowed taste",
    images: [],
    categoryId: "cat_whiskey",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_whi007_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_whi007_bottle",
        name: "Bottle",
        price: 90,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "WHI007",
  },

  // ===========================================================================
  // RUM (4 items) - cat_rum - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_rum001",
    name: "Black Spirits White",
    description: "White rum with clean, crisp flavor",
    images: [],
    categoryId: "cat_rum",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rum001_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rum001_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "RUM001",
  },
  {
    id: "item_rum002",
    name: "Captain Morgan Dark",
    description: "Dark rum with rich, full-bodied flavor",
    images: [],
    categoryId: "cat_rum",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rum002_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rum002_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "RUM002",
  },
  {
    id: "item_rum003",
    name: "Captain Morgan Spiced",
    description: "Spiced rum with vanilla and caramel notes",
    images: [],
    categoryId: "cat_rum",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rum003_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rum003_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "RUM003",
  },
  {
    id: "item_rum004",
    name: "Four Palm",
    description: "Premium aged rum with complex flavors",
    images: [],
    categoryId: "cat_rum",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rum004_shot",
        name: "Shot",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rum004_bottle",
        name: "Bottle",
        price: 160,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "RUM004",
  },

  // ===========================================================================
  // LIQUEURS (10 items) - cat_liqueurs - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_liq001",
    name: "Amarula",
    description: "Cream liqueur with marula fruit flavor",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq001_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq001_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "LIQ001",
  },
  {
    id: "item_liq002",
    name: "Jägermeister",
    description: "Herbal liqueur with 56 botanicals",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq002_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq002_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "LIQ002",
  },
  {
    id: "item_liq003",
    name: "Triple Sec",
    description: "Orange-flavored liqueur for cocktails",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq003_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq003_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ003",
  },
  {
    id: "item_liq004",
    name: "Limoncello",
    description: "Italian lemon liqueur with zesty flavor",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq004_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq004_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ004",
  },
  {
    id: "item_liq005",
    name: "Tia Maria",
    description: "Coffee liqueur with Jamaican rum base",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq005_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq005_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ005",
  },
  {
    id: "item_liq006",
    name: "Bols Pepper",
    description: "Pepper-flavored liqueur with spicy kick",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq006_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq006_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ006",
  },
  {
    id: "item_liq007",
    name: "Blue Curaçao",
    description: "Blue orange liqueur for colorful cocktails",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq007_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq007_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ007",
  },
  {
    id: "item_liq008",
    name: "Bols Melon",
    description: "Melon-flavored liqueur with sweet taste",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq008_shot",
        name: "Shot",
        price: 2,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq008_bottle",
        name: "Bottle",
        price: 55,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ008",
  },
  {
    id: "item_liq009",
    name: "Crème de Cacao",
    description: "Chocolate liqueur with rich cocoa flavor",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq009_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq009_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "LIQ009",
  },
  {
    id: "item_liq010",
    name: "Amaretto Disaronno",
    description: "Italian almond liqueur with sweet, nutty flavor",
    images: [],
    categoryId: "cat_liqueurs",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_liq010_shot",
        name: "Shot",
        price: 3,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_liq010_bottle",
        name: "Bottle",
        price: 80,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: ["nuts"],
    isAvailable: true,
    isPopular: true,
    sku: "LIQ010",
  },

  // ===========================================================================
  // BOOSTERS (3 items) - cat_boosters
  // ===========================================================================
  {
    id: "item_bst001",
    name: "Cold & Flu Fighter",
    description: "Pineapple, garlic, fresh ginger",
    images: [],
    categoryId: "cat_boosters",
    kitchenSection: "bar",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "BST001",
  },
  {
    id: "item_bst002",
    name: "Wellness",
    description: "Lemon, ginger, turmeric, black pepper",
    images: [],
    categoryId: "cat_boosters",
    kitchenSection: "bar",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "BST002",
  },
  {
    id: "item_bst003",
    name: "Body Cleaner",
    description: "Cucumber, banana, spinach, coconut cream, lemon, pineapple",
    images: [],
    categoryId: "cat_boosters",
    kitchenSection: "bar",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "BST003",
  },

  // ===========================================================================
  // MILKSHAKES (5 items) - cat_milkshakes
  // ===========================================================================
  {
    id: "item_mlk001",
    name: "Vanilla Milkshake",
    description: "Vanilla ice cream, milk",
    images: [],
    categoryId: "cat_milkshakes",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MLK001",
  },
  {
    id: "item_mlk002",
    name: "Strawberry Milkshake",
    description: "Strawberry ice cream, milk",
    images: [],
    categoryId: "cat_milkshakes",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MLK002",
  },
  {
    id: "item_mlk003",
    name: "Chocolate Milkshake",
    description: "Chocolate ice cream, milk",
    images: [],
    categoryId: "cat_milkshakes",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MLK003",
  },
  {
    id: "item_mlk004",
    name: "Banana Milkshake",
    description: "Vanilla ice cream, banana, milk",
    images: [],
    categoryId: "cat_milkshakes",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MLK004",
  },
  {
    id: "item_mlk005",
    name: "Coffee Milkshake",
    description: "Chocolate ice cream, milk, coffee powder",
    images: [],
    categoryId: "cat_milkshakes",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "MLK005",
  },

  // ===========================================================================
  // SMOKERS (1 item) - cat_smokers
  // ===========================================================================
  {
    id: "item_smk001",
    name: "Hookah / Shisha",
    description: "Traditional water pipe for smoking flavored tobacco",
    images: [],
    categoryId: "cat_smokers",
    kitchenSection: "bar",
    basePrice: 20,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "SMK001",
  },
];

// Seed function
async function seedBeverageItems() {
  console.log("\n🍹 Seeding Beverage Items - Part 3 (37 items)...\n");
  const batch = db.batch();
  const now = new Date();

  for (const item of beverageItems) {
    const { id, ...data } = item;
    const docRef = db.collection(COLLECTION).doc(id);
    batch.set(docRef, { ...data, createdAt: now, updatedAt: now });
    console.log(`📝 ${item.name} (${item.sku})`);
  }

  await batch.commit();
  console.log(`\n✅ Seeded ${beverageItems.length} beverage items!\n`);
}

seedBeverageItems()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  });
