/**
 * Beverage Menu Items Seeder - Part 2 (Items 31-60)
 * Cocktails (22) + Red Wines (3) + White Wines (2) + Sparkling Wines (3)
 * Run: npx tsx scripts/seedBeverageItems-part2.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "barMenuItems";

const beverageItems = [
  // ===========================================================================
  // COCKTAILS (22 items continued) - cat_cocktails
  // ===========================================================================
  {
    id: "item_coc003",
    name: "Mint Tequila Fizz",
    description: "Tequila, mint, ginger soda, lime juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC003",
  },
  {
    id: "item_coc004",
    name: "Metadoor Sour",
    description: "Tequila, pineapple juice, lime juice, sugar syrup",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC004",
  },
  {
    id: "item_coc005",
    name: "Gin & Tonic",
    description: "Gin with tonic water",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC005",
  },
  {
    id: "item_coc006",
    name: "Negroni",
    description: "Gin, Campari, Martini Rosso, orange",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC006",
  },
  {
    id: "item_coc007",
    name: "Magic Spicy",
    description: "Spiced rum, dark rum, Campari, pineapple juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC007",
  },
  {
    id: "item_coc008",
    name: "Moscow Mule",
    description: "Vodka, lime, ginger beer",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC008",
  },
  {
    id: "item_coc009",
    name: "Aperol Spritz",
    description: "Aperol, sparkling wine, soda water, orange slice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "COC009",
  },
  {
    id: "item_coc010",
    name: "Dawa",
    description: "Konyagi, lime juice, honey, ginger beer",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC010",
  },
  {
    id: "item_coc011",
    name: "Tequila Sunrise",
    description: "Tequila, orange juice, lime juice, grenadine",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC011",
  },
  {
    id: "item_coc012",
    name: "Caipirinha",
    description: "Cachaça, lime wedges, sugar",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC012",
  },
  {
    id: "item_coc013",
    name: "Mai Tai",
    description:
      "White rum, dark rum, orange, pineapple juice, amaretto, Angostura, lime juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC013",
  },
  {
    id: "item_coc014",
    name: "Daiquiri",
    description: "White rum, lime juice, sugar",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC014",
  },
  {
    id: "item_coc015",
    name: "Espresso Martini",
    description: "Vodka, espresso coffee, Kahlúa",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC015",
  },
  {
    id: "item_coc016",
    name: "Cosmopolitan",
    description: "Vodka, triple sec, lime juice, cranberry juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC016",
  },
  {
    id: "item_coc017",
    name: "Sex on the Beach",
    description: "Vodka, triple sec, orange juice, lime juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC017",
  },
  {
    id: "item_coc018",
    name: "Blue Hawaii",
    description: "White rum, vodka, blue curaçao, pineapple juice",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC018",
  },
  {
    id: "item_coc019",
    name: "Old Fashioned",
    description: "Whiskey, sugar, Angostura bitters",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC019",
  },
  {
    id: "item_coc020",
    name: "Sweet Fameica",
    description: "Vodka, passion juice, four-seed syrup, vanilla flavour",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC020",
  },
  {
    id: "item_coc021",
    name: "Jungle Bird",
    description: "Dark rum, Campari, pineapple juice, lime juice, sugar syrup",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC021",
  },
  {
    id: "item_coc022",
    name: "Cucumber Martini",
    description: "Vodka, cucumber slice, lime juice, simple syrup",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "COC022",
  },
  {
    id: "item_coc023",
    name: "Aperol Sour",
    description: "Aperol, gin, lime juice, egg white, simple syrup",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["eggs"],
    isAvailable: true,
    isPopular: false,
    sku: "COC023",
  },
  {
    id: "item_coc024",
    name: "Long Island Iced Tea",
    description: "Vodka, gin, white rum, triple sec, tequila, Coke, lemon",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC024",
  },

  // ===========================================================================
  // RED WINES (3 items continued) - cat_red_wines - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_rwi004",
    name: "Arniston Bay Shiraz",
    description: "South African Shiraz with rich berry flavors",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi004_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi004_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "RWI004",
  },
  {
    id: "item_rwi005",
    name: "Star of Africa Merlot",
    description: "Smooth Merlot with plum and chocolate notes",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi005_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi005_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "RWI005",
  },
  {
    id: "item_rwi006",
    name: "Gato Negro Rosé",
    description: "Chilean rosé with fresh and fruity character",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi006_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi006_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "RWI006",
  },

  // ===========================================================================
  // WHITE WINES (2 items continued) - cat_white_wines - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_wwi004",
    name: "Kleine Zalze Chenin",
    description: "South African Chenin Blanc with tropical fruit notes",
    images: [],
    categoryId: "cat_white_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_wwi004_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_wwi004_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "WWI004",
  },
  {
    id: "item_wwi005",
    name: "Eluxio Pinot Grigio",
    description: "Italian Pinot Grigio with crisp citrus flavors",
    images: [],
    categoryId: "cat_white_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_wwi005_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_wwi005_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "WWI005",
  },

  // ===========================================================================
  // SPARKLING WINES (3 items) - cat_sparkling_wines - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_spw001",
    name: "Provetto Brut",
    description: "Italian sparkling wine with fine bubbles",
    images: [],
    categoryId: "cat_sparkling_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_spw001_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_spw001_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "SPW001",
  },
  {
    id: "item_spw002",
    name: "Pol Remy Brut",
    description: "French style brut with elegant finish",
    images: [],
    categoryId: "cat_sparkling_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_spw002_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_spw002_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "SPW002",
  },
  {
    id: "item_spw003",
    name: "Martini DOC Prosecco",
    description: "Premium Italian Prosecco with fresh fruit aromas",
    images: [],
    categoryId: "cat_sparkling_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_spw003_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_spw003_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "SPW003",
  },
];

// Seed function
async function seedBeverageItems() {
  console.log("\n🍹 Seeding Beverage Items - Part 2 (30 items)...\n");
  const batch = db.batch();
  const now = new Date();

  for (const item of beverageItems) {
    const { id, ...data } = item;
    const docRef = db.collection(COLLECTION).doc(id);
    batch.set(docRef, { ...data, createdAt: now, updatedAt: now });
    console.log(`📝 ${item.name} (${item.sku})`);
  }

  await batch.commit();
  console.log(`\n✅ Seeded ${beverageItems.length} beverage items!\n`);
}

seedBeverageItems()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  });
