/**
 * Menu Items Seeder - Part 4 (Items 92-116)
 * Desserts + Night Food Menu (Starters, Main, Dessert)
 * Run: npx tsx scripts/seedMenuItems-part4.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

const menuItems = [
  // DESSERTS (10 items)
  {
    id: "mi_dessert_cake_of_day",
    name: "Cake of the day",
    description: "",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "eggs"],
    isAvailable: true,
    isPopular: false,
    sku: "CKD006",
    images: [],
  },
  {
    id: "mi_dessert_cheesecake",
    name: "Cheese cake",
    description: "Cheese cream, sour cream.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "CSK006",
    images: [],
  },
  {
    id: "mi_dessert_tiramisu",
    name: "Tiramisu",
    description: "Whipping cream, Mascarpone cheese, Cheese, cream.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "gluten", "eggs"],
    isAvailable: true,
    isPopular: true,
    sku: "TRM006",
    images: [],
  },
  {
    id: "mi_dessert_chocolate_grass",
    name: "Chocolate grass",
    description: "Dark Choco, White Choco, Brown Choco, Whipping cream.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "CHG006",
    images: [],
  },
  {
    id: "mi_dessert_fruits_salad",
    name: "Fruits salad",
    description: "Cubes of mix seasonal fruits.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true, nightItemId: "mi_night_fruit_salad" },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "FRS010",
    images: [],
  },
  {
    id: "mi_dessert_fruit_platter",
    name: "Fruit platter",
    description: "Mix of seasonal fruits.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "FRP006",
    images: [],
  },
  {
    id: "mi_dessert_ice_cream",
    name: "Ice cream of your choice",
    description: "Vanilla, strawberry or chocolate.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_icecream_vanilla",
        name: "Vanilla",
        price: 9,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_icecream_strawberry",
        name: "Strawberry",
        price: 9,
        isAvailable: true,
        sortOrder: 2,
      },
      {
        id: "var_icecream_chocolate",
        name: "Chocolate",
        price: 9,
        isAvailable: true,
        sortOrder: 3,
      },
    ],
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "ICM009",
    images: [],
  },
  {
    id: "mi_dessert_rice_kheer",
    name: "Rice kheer",
    description: "Rice, milk, sugar and dry fruits.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 9,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "nuts"],
    isAvailable: true,
    isPopular: false,
    sku: "RKH009",
    images: [],
  },
  {
    id: "mi_dessert_gajar_halwa",
    name: "Gajar ka halwa",
    description: "Carrot, milk, sugar and dry fruits.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 9,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "nuts"],
    isAvailable: true,
    isPopular: false,
    sku: "GJH009",
    images: [],
  },
  {
    id: "mi_dessert_shahi_tukda",
    name: "Shahi tukda",
    description: "Bread, milk and sugar.",
    categoryId: "cat_desserts",
    kitchenSection: "pastry",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "SHT007",
    images: [],
  },

  // NIGHT MENU - STARTERS (5 items)
  {
    id: "mi_night_bruschetta",
    name: "BRUSCHETTA",
    description:
      "Three pieces of bread with choices of avocado tomato and olives on top.",
    categoryId: "cat_night_starters",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "NBR006",
    images: [],
  },
  {
    id: "mi_night_veg_samosa",
    name: "VEG SAMOSA",
    description:
      "Mix of carrot, bell pepper, onion, zuchini, potato and broccoli.",
    categoryId: "cat_night_starters",
    kitchenSection: "night",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "NVS005",
    images: [],
  },
  {
    id: "mi_night_chicken_samosa",
    name: "CHICKEN SAMOSA",
    description: "Chicken chopped with onion covered with samosa sheet.",
    categoryId: "cat_night_starters",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "NCS006",
    images: [],
  },
  {
    id: "mi_night_veg_sandwich",
    name: "VEG SANDWICH",
    description:
      "Slices of tomato, onion, cucumber, carrot and zuchini covered with toast bread & cheese.",
    categoryId: "cat_night_starters",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with chips.",
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NVW006",
    images: [],
  },
  {
    id: "mi_night_chicken_sandwich",
    name: "CHICKEN SANDWICH",
    description:
      "Slices of tomato, onion, cucumber, carrot and zuchini covered with toast bread & cheese.",
    categoryId: "cat_night_starters",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with chips.",
    nightMenu: { isAvailable: true },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NCW006",
    images: [],
  },

  // NIGHT MENU - MAIN (6 items)
  {
    id: "mi_night_chicken_curry",
    name: "CHICKEN CURRY",
    description: "Chicken cubes cooked with curry and spice in tomato sauce.",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [
      {
        groupName: "Served with",
        required: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { name: "Rice", priceMod: 0, isAvailable: true },
          { name: "Chapati", priceMod: 0, isAvailable: true },
        ],
      },
    ],
    nightMenu: { isAvailable: true },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "NCC010",
    images: [],
  },
  {
    id: "mi_night_chips_mayai",
    name: "CHIPS MAYAI",
    description: "French fries mix with Egg fried together.",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with salad.",
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["eggs"],
    isAvailable: true,
    isPopular: false,
    sku: "NCM006",
    images: [],
  },
  {
    id: "mi_night_plain_chips",
    name: "PLAIN CHIPS",
    description: "French fries.",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with salad.",
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "NPC005",
    images: [],
  },
  {
    id: "mi_night_plain_rice",
    name: "PLAIN RICE",
    description: "",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 4,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with swahili salad and coconut sauce.",
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "NPR004",
    images: [],
  },
  {
    id: "mi_night_margarita_pizza",
    name: "MARGHERITA PIZZA",
    description: "Tomato sauce, Mozzarella cheese.",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NMP010",
    images: [],
  },
  {
    id: "mi_night_hawaiian_pizza",
    name: "HAWAIAN PIZZA",
    description: "Chicken, Pineapple, Cheese.",
    categoryId: "cat_night_main",
    kitchenSection: "night",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NHP015",
    images: [],
  },

  // NIGHT MENU - DESSERT (4 items)
  {
    id: "mi_night_vanilla_ice_cream",
    name: "VANILLA ICE CREAM",
    description: "",
    categoryId: "cat_night_dessert",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NIC006",
    images: [],
  },
  {
    id: "mi_night_chocolate_ice_cream",
    name: "CHOCOLATE ICE CREAM",
    description: "",
    categoryId: "cat_night_dessert",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NCH006",
    images: [],
  },
  {
    id: "mi_night_strawberry_ice_cream",
    name: "STRAWBERRY ICE CREAM",
    description: "",
    categoryId: "cat_night_dessert",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "NST006",
    images: [],
  },
  {
    id: "mi_night_fruit_salad",
    name: "FRUIT SALAD",
    description: "",
    categoryId: "cat_night_dessert",
    kitchenSection: "night",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: true },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "NFS006",
    images: [],
  },
];

async function seed() {
  console.log("🚀 Seeding Part 4 (25 items)...\n");
  const now = new Date();
  const batch = db.batch();
  for (const item of menuItems) {
    const { id, ...data } = item;
    batch.set(db.collection(COLLECTION).doc(id), {
      ...data,
      createdAt: now,
      updatedAt: now,
    });
    console.log(`📝 ${item.name}`);
  }
  await batch.commit();
  console.log(`\n✅ Part 4 complete: ${menuItems.length} items seeded!`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
