/**
 * Menu Items Seeder - Part 1 (Items 1-24)
 * Breakfast + Soups + Appetizers
 * Run: npx tsx scripts/seedMenuItems-part1.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

const menuItems = [
  // BREAKFAST (2 items)
  {
    id: "mi_breakfast_menu",
    name: "BREAKFAST MENU",
    description:
      "Complete breakfast set with egg of your choice, sides, and selection of hot drinks.",
    categoryId: "cat_breakfast",
    kitchenSection: "breakfast",
    basePrice: 25,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [
      {
        groupName: "Egg of your choice",
        required: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { name: "Plain Omelet", priceMod: 0, isAvailable: true },
          { name: "Spanish Omelet", priceMod: 0, isAvailable: true },
          { name: "Scramble Egg", priceMod: 0, isAvailable: true },
          { name: "Poached Egg", priceMod: 0, isAvailable: true },
          { name: "Fried Egg", priceMod: 0, isAvailable: true },
          { name: "Boiled Egg", priceMod: 0, isAvailable: true },
          { name: "Mushroom Omelet", priceMod: 0, isAvailable: true },
          { name: "Cheese Omelet", priceMod: 0, isAvailable: true },
        ],
      },
      {
        groupName: "SIDES",
        required: false,
        minSelect: 0,
        maxSelect: null,
        options: [
          { name: "Baked beans", priceMod: 0, isAvailable: true },
          { name: "Sauteed mushrooms", priceMod: 0, isAvailable: true },
          { name: "Sauteed vegetables", priceMod: 0, isAvailable: true },
          { name: "Chicken sausages", priceMod: 0, isAvailable: true },
          { name: "Potatoes wedges", priceMod: 0, isAvailable: true },
          { name: "Grilled tomatoes", priceMod: 0, isAvailable: true },
          { name: "Toast bread", priceMod: 0, isAvailable: true },
        ],
      },
      {
        groupName: "FRENCH TOAST / WAFFLES",
        required: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { name: "French toast - Nutella", priceMod: 0, isAvailable: true },
          {
            name: "French toast - Maple syrup",
            priceMod: 0,
            isAvailable: true,
          },
          { name: "French toast - Honey", priceMod: 0, isAvailable: true },
          { name: "Waffles - Nutella", priceMod: 0, isAvailable: true },
          { name: "Waffles - Maple syrup", priceMod: 0, isAvailable: true },
          { name: "Waffles - Honey", priceMod: 0, isAvailable: true },
        ],
      },
      {
        groupName: "PANCAKES",
        required: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { name: "Pancakes - Nutella", priceMod: 0, isAvailable: true },
          { name: "Pancakes - Maple syrup", priceMod: 0, isAvailable: true },
          { name: "Pancakes - Jam", priceMod: 0, isAvailable: true },
          { name: "Pancakes - Honey", priceMod: 0, isAvailable: true },
        ],
      },
      {
        groupName: "SWAHILI SIDES",
        required: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { name: "Cassava", priceMod: 0, isAvailable: true },
          { name: "Sweet potatoes", priceMod: 0, isAvailable: true },
          { name: "Green banana", priceMod: 0, isAvailable: true },
          { name: "Chapatti", priceMod: 0, isAvailable: true },
        ],
      },
      {
        groupName: "INDIAN DISH",
        required: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          {
            name: "Idli & Sambhar",
            priceMod: 0,
            isAvailable: true,
            description: "Indian delicious food",
          },
          {
            name: "Choices of Parathas",
            priceMod: 0,
            isAvailable: true,
            description: "Indian delicious food",
          },
        ],
      },
      {
        groupName: "SELECTION OF HOT DRINKS",
        required: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { name: "Oat porridge", priceMod: 0, isAvailable: true },
          { name: "Black Tea", priceMod: 0, isAvailable: true },
          { name: "Masala Tea", priceMod: 0, isAvailable: true },
          { name: "Hibiscus Tea", priceMod: 0, isAvailable: true },
          { name: "Chamomile Tea", priceMod: 0, isAvailable: true },
        ],
      },
    ],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["eggs", "gluten", "dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "BFM025",
    images: [],
  },
  {
    id: "mi_brewed_coffee",
    name: "BREWED COFFEE",
    description: "Cappuccino, Americano, Expresso and Latte.",
    categoryId: "cat_breakfast",
    kitchenSection: "breakfast",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_cappuccino",
        name: "Cappuccino",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_americano",
        name: "Americano",
        price: 8,
        isAvailable: true,
        sortOrder: 2,
      },
      {
        id: "var_expresso",
        name: "Expresso",
        price: 8,
        isAvailable: true,
        sortOrder: 3,
      },
      {
        id: "var_latte",
        name: "Latte",
        price: 8,
        isAvailable: true,
        sortOrder: 4,
      },
    ],
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "BFC008",
    images: [],
  },

  // SOUPS (8 items)
  {
    id: "mi_soup_seafood",
    name: "Seafood soup",
    description: "Fish, Octopus, Prawns, mix with vegetables.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "SFS008",
    images: [],
  },
  {
    id: "mi_soup_leeks_potato",
    name: "Cream of Leeks and Potato soup",
    description: "Potatoes, Leeks, Onion, Garlic, Ginger and Cream.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CLP006",
    images: [],
  },
  {
    id: "mi_soup_carrot_zucchini",
    name: "Cream of Carrot and Zucchini soup",
    description: "Carrot, Onion, Ginger, Zucchini and Cream.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CCZ006",
    images: [],
  },
  {
    id: "mi_soup_chicken_swahili",
    name: "Chicken Swahili soup",
    description: "Chicken bones, Garlic, Ginger and Vegetable.",
    categoryId: "cat_soups",
    kitchenSection: "swahili",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "CSW007",
    images: [],
  },
  {
    id: "mi_soup_pumpkin",
    name: "Cream of Pumpkin soup",
    description: "Pumpkin, Leeks, Garlic, Ginger and Cream.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CPK006",
    images: [],
  },
  {
    id: "mi_soup_mixed_vegetable",
    name: "Mixed Vegetable soup",
    description:
      "Carrot, Zucchini, Broccoli, Potatoes, Bell pepper, Garlic, Onion, Ginger, Cream.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "MVS006",
    images: [],
  },
  {
    id: "mi_soup_tomato",
    name: "Cream of Tomato soup",
    description: "Fresh tomato, Onion, Garlic, Cream.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CTS006",
    images: [],
  },
  {
    id: "mi_soup_chicken_mushroom",
    name: "Chicken and Mushroom soup",
    description:
      "Chicken, Mushroom, Carrot, Bell pepper, Onion, Garlic, Ginger.",
    categoryId: "cat_soups",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "CMS007",
    images: [],
  },

  // APPETIZERS (8 items)
  {
    id: "mi_appetizer_chicken_finger",
    name: "Chicken finger",
    description: "",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "CKF006",
    images: [],
  },
  {
    id: "mi_appetizer_spring_rolls",
    name: "Spring rolls",
    description: "Chicken or vegetable.",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_spring_rolls_chicken",
        name: "Chicken",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_spring_rolls_vegetable",
        name: "Vegetable",
        price: 6,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "soy"],
    isAvailable: true,
    isPopular: false,
    sku: "SRL006",
    images: [],
  },
  {
    id: "mi_appetizer_samosa",
    name: "Samosa",
    description: "",
    categoryId: "cat_appetizers",
    kitchenSection: "indian",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "SMS006",
    images: [],
  },
  {
    id: "mi_appetizer_bruschetta",
    name: "Bruschetta",
    description: "With choice of: Avocado or Tomato & Olives.",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_bruschetta_avocado",
        name: "Avocado",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_bruschetta_tomato_olives",
        name: "Tomato & Olives",
        price: 6,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    nightMenu: { isAvailable: true, nightItemId: "mi_night_bruschetta" },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "BRS006",
    images: [],
  },
  {
    id: "mi_appetizer_sesame_fish",
    name: "Sesame fish",
    description: "",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish", "sesame"],
    isAvailable: true,
    isPopular: false,
    sku: "SMF007",
    images: [],
  },
  {
    id: "mi_appetizer_tuna_tataki",
    name: "Tuna tataki",
    description: "",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish", "soy"],
    isAvailable: true,
    isPopular: false,
    sku: "TNT007",
    images: [],
  },
  {
    id: "mi_appetizer_prawns_tempura",
    name: "Prawns' tempura",
    description: "",
    categoryId: "cat_appetizers",
    kitchenSection: "continental",
    basePrice: 7,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "PRT007",
    images: [],
  },
  {
    id: "mi_appetizer_zanzibar_kachori",
    name: "Zanzibar kachori",
    description: "With chilli dip.",
    categoryId: "cat_appetizers",
    kitchenSection: "swahili",
    basePrice: 5,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "ZKC005",
    images: [],
  },

  // INDIAN STARTERS (6 items)
  {
    id: "mi_indian_starter_seekh_kebab",
    name: "Chicken Seekh Kebab",
    description:
      "Chopped chicken, ginger garlic, cheese, egg, coriander, onion.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["eggs", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CSK010",
    images: [],
  },
  {
    id: "mi_indian_starter_samosa",
    name: "Samosa",
    description: "Chicken, vegetable or potatoes.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_indian_samosa_chicken",
        name: "Chicken",
        price: 10,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_indian_samosa_vegetable",
        name: "Vegetable",
        price: 10,
        isAvailable: true,
        sortOrder: 2,
      },
      {
        id: "var_indian_samosa_potatoes",
        name: "Potatoes",
        price: 10,
        isAvailable: true,
        sortOrder: 3,
      },
    ],
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "ISM010",
    images: [],
  },
  {
    id: "mi_indian_starter_afgani_chicken",
    name: "Afgani chicken",
    description: "Cashew nuts, egg, cheese, white cream sauce, white pepper.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["nuts", "eggs", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "AFC010",
    images: [],
  },
  {
    id: "mi_indian_starter_tandoori_chicken",
    name: "Tandoori chicken",
    description: "Yoghurt, mustard oil, chilli.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "mustard"],
    isAvailable: true,
    isPopular: false,
    sku: "TDC010",
    images: [],
  },
  {
    id: "mi_indian_starter_kalmi_kebab",
    name: "Kalmi Kebab",
    description: "Cashew nuts, eggs, cheese, white cream sauce, green chilli.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["nuts", "eggs", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "KMK010",
    images: [],
  },
  {
    id: "mi_indian_starter_paneer_tikka",
    name: "Paneer tikka",
    description: "Yoghurt, mustard oil, chilli, onion, tomato.",
    categoryId: "cat_indian_starters",
    kitchenSection: "indian",
    basePrice: 19,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "mustard"],
    isAvailable: true,
    isPopular: false,
    sku: "PTK019",
    images: [],
  },
];

async function seed() {
  console.log("🚀 Seeding Part 1 (24 items)...\n");
  const now = new Date();
  const batch = db.batch();
  for (const item of menuItems) {
    const { id, ...data } = item;
    batch.set(db.collection(COLLECTION).doc(id), {
      ...data,
      createdAt: now,
      updatedAt: now,
    });
    console.log(`📝 ${item.name}`);
  }
  await batch.commit();
  console.log(`\n✅ Part 1 complete: ${menuItems.length} items seeded!`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
