/**
 * Menu Items Seeder - Part 3 (Items 58-91)
 * Sandwiches + Wraps + Main Course (Seafood/Chicken/Others) + Swahili + Special Orders + Pasta
 * Run: npx tsx scripts/seedMenuItems-part3.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

// Reusable groups
const COOKING_STYLE_GROUP = {
  groupName: "Cooking Style",
  required: true,
  minSelect: 1,
  maxSelect: 1,
  options: [
    { name: "Grilled", priceMod: 0, isAvailable: true },
    { name: "Fried", priceMod: 0, isAvailable: true },
    { name: "Baked", priceMod: 0, isAvailable: true },
    { name: "Pan Fried", priceMod: 0, isAvailable: true },
    { name: "Masala", priceMod: 0, isAvailable: true },
    { name: "Curry", priceMod: 0, isAvailable: true },
  ],
};
const SIDE_DISH_GROUP = {
  groupName: "Side Dish",
  required: true,
  minSelect: 1,
  maxSelect: 1,
  options: [
    { name: "Rice", priceMod: 0, isAvailable: true },
    { name: "Risotto", priceMod: 0, isAvailable: true },
    { name: "Mashed potatoes", priceMod: 0, isAvailable: true },
    { name: "French fries", priceMod: 0, isAvailable: true },
    { name: "Potato wedges", priceMod: 0, isAvailable: true },
    { name: "Vegetables", priceMod: 0, isAvailable: true },
  ],
};
const SPECIAL_SIDE_GROUP = {
  groupName: "Side Choice",
  required: true,
  minSelect: 1,
  maxSelect: 1,
  options: [
    { name: "Rice", priceMod: 0, isAvailable: true },
    { name: "Potato wedges", priceMod: 0, isAvailable: true },
    { name: "Mashed potato", priceMod: 0, isAvailable: true },
    { name: "French fries", priceMod: 0, isAvailable: true },
  ],
};
const PASTA_SAUCE_GROUP = {
  groupName: "Sauce",
  required: true,
  minSelect: 1,
  maxSelect: 1,
  options: [
    { name: "Tomato sauce", priceMod: 0, isAvailable: true },
    { name: "White cream sauce", priceMod: 0, isAvailable: true },
    { name: "Herb sauce", priceMod: 0, isAvailable: true },
  ],
};

const menuItems = [
  // SANDWICHES (5 items)
  {
    id: "mi_sandwich_new_york_club",
    name: "New York club sandwich",
    description: "Fresh tomato, cucumber, onions, eggs, chicken & cheese.",
    categoryId: "cat_sandwiches",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "eggs"],
    isAvailable: true,
    isPopular: false,
    sku: "NYC012",
    images: [],
  },
  {
    id: "mi_sandwich_tuna",
    name: "Tuna sandwich",
    description: "Tuna, cucumber, onion & tomato.",
    categoryId: "cat_sandwiches",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "fish"],
    isAvailable: true,
    isPopular: false,
    sku: "TNS010",
    images: [],
  },
  {
    id: "mi_sandwich_egg",
    name: "Egg sandwich",
    description: "Eggs, tomato, cucumber, onion & cheese.",
    categoryId: "cat_sandwiches",
    kitchenSection: "continental",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "eggs"],
    isAvailable: true,
    isPopular: false,
    sku: "EGS008",
    images: [],
  },
  {
    id: "mi_sandwich_chicken",
    name: "Chicken sandwich",
    description: "Cucumber, onion, tomato, chicken & cheese.",
    categoryId: "cat_sandwiches",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: true, nightItemId: "mi_night_chicken_sandwich" },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "CKS010",
    images: [],
  },
  {
    id: "mi_sandwich_vegetable",
    name: "Vegetable sandwich",
    description: "Tomato, onion, carrot, zucchini & cheese.",
    categoryId: "cat_sandwiches",
    kitchenSection: "continental",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: true, nightItemId: "mi_night_veg_sandwich" },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "VGS008",
    images: [],
  },

  // WRAPS (3 items)
  {
    id: "mi_wrap_chicken",
    name: "Chicken wrap",
    description: "Chicken & vegetables wrapped with chapati.",
    categoryId: "cat_wraps",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "WRC010",
    images: [],
  },
  {
    id: "mi_wrap_vegetable",
    name: "Vegetable wrap",
    description: "Onion, bell pepper, carrot, cauliflower & broccoli.",
    categoryId: "cat_wraps",
    kitchenSection: "continental",
    basePrice: 8,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: ["gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "WRV008",
    images: [],
  },
  {
    id: "mi_wrap_seafood",
    name: "Seafood wrap",
    description: "Mix of fish, calamari & octopus.",
    categoryId: "cat_wraps",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with French fries & salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "fish", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "WRS012",
    images: [],
  },

  // MAIN COURSE - SEAFOODS (5 items)
  {
    id: "mi_main_tuna",
    name: "Tuna",
    description: "Main course seafood, $15 per piece.",
    categoryId: "cat_main_seafoods",
    kitchenSection: "seafood",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish"],
    isAvailable: true,
    isPopular: false,
    sku: "MCT015",
    images: [],
  },
  {
    id: "mi_main_king_fish",
    name: "King fish",
    description: "Main course seafood, $15 per piece.",
    categoryId: "cat_main_seafoods",
    kitchenSection: "seafood",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish"],
    isAvailable: true,
    isPopular: false,
    sku: "MCK015",
    images: [],
  },
  {
    id: "mi_main_calamari",
    name: "Calamari",
    description: "Main course seafood, $15 per piece.",
    categoryId: "cat_main_seafoods",
    kitchenSection: "seafood",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "MCC015",
    images: [],
  },
  {
    id: "mi_main_octopus",
    name: "Octopus",
    description: "Main course seafood, $15 per piece.",
    categoryId: "cat_main_seafoods",
    kitchenSection: "seafood",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "MCO015",
    images: [],
  },
  {
    id: "mi_main_king_prawns",
    name: "King prawns",
    description: "Main course seafood, $15 per piece.",
    categoryId: "cat_main_seafoods",
    kitchenSection: "seafood",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "MCP015",
    images: [],
  },

  // MAIN COURSE - CHICKEN (2 items)
  {
    id: "mi_main_chicken_leg",
    name: "Chicken leg",
    description: "Main course chicken, $13 per piece.",
    categoryId: "cat_main_chicken",
    kitchenSection: "continental",
    basePrice: 13,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MCL013",
    images: [],
  },
  {
    id: "mi_main_chicken_breast",
    name: "Chicken breast",
    description: "Main course chicken, $13 per piece.",
    categoryId: "cat_main_chicken",
    kitchenSection: "continental",
    basePrice: 13,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [COOKING_STYLE_GROUP, SIDE_DISH_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MCB013",
    images: [],
  },

  // MAIN COURSE - OTHERS (3 items)
  {
    id: "mi_main_chicken_fried_rice",
    name: "Chicken fried rice",
    description:
      "Chicken, Rice, Vegetable, Garlic, Ginger, Mamacita, Soya sauce.",
    categoryId: "cat_main_others",
    kitchenSection: "continental",
    basePrice: 13,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["soy", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "MCF013",
    images: [],
  },
  {
    id: "mi_main_chicken_pasta",
    name: "Chicken Pasta",
    description:
      "Chicken, Pasta, Vegetable, Garlic, Ginger, Mamacita, Soya sauce.",
    categoryId: "cat_main_others",
    kitchenSection: "continental",
    basePrice: 13,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "soy"],
    isAvailable: true,
    isPopular: false,
    sku: "MCP013",
    images: [],
  },
  {
    id: "mi_main_chicken_schnitzer",
    name: "Chicken Schnitzer",
    description: "Marinated chicken, Eggs, Wheat flour, Bread crumbs.",
    categoryId: "cat_main_others",
    kitchenSection: "continental",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with vegetable and chips.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["eggs", "gluten"],
    isAvailable: true,
    isPopular: false,
    sku: "MCS015",
    images: [],
  },

  // SWAHILI DISHES (7 items)
  {
    id: "mi_swahili_fried_changu",
    name: "Fried changu",
    description: "",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 20,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with spinach in coconut sauce & rice.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish"],
    isAvailable: true,
    isPopular: true,
    sku: "FRC020",
    images: [],
  },
  {
    id: "mi_swahili_roast_chicken",
    name: "Roast chicken",
    description: "",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with ugali & Swahili salad.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "RSC015",
    images: [],
  },
  {
    id: "mi_swahili_octopus_coconut",
    name: "Octopus in coconut sauce",
    description: "",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with Swahili chapati.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "OCC015",
    images: [],
  },
  {
    id: "mi_swahili_green_banana_mutton",
    name: "Green banana & mutton",
    description: "Mixed of green banana & mutton with coconut curry sauce.",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "GBM015",
    images: [],
  },
  {
    id: "mi_swahili_zanzibar_pilau",
    name: "Zanzibar pilau",
    description: "Rice mixed with spices & vegetables.",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with salad.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "ZNP012",
    images: [],
  },
  {
    id: "mi_swahili_calamari_stew",
    name: "Calamari stew",
    description: "Calamari with vegetables & tomato sauce.",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with rice.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "CLS015",
    images: [],
  },
  {
    id: "mi_swahili_beans",
    name: "Beans",
    description: "Red beans in coconut sauce.",
    categoryId: "cat_swahili_dishes",
    kitchenSection: "swahili",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    hasGroups: false,
    servedWith: "Served with rice.",
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "BNS010",
    images: [],
  },

  // SPECIAL ORDERS (4 items)
  {
    id: "mi_special_sultan_chicken_platter",
    name: "Sultan special chicken platter",
    description: "",
    categoryId: "cat_special_orders",
    kitchenSection: "continental",
    basePrice: 35,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [SPECIAL_SIDE_GROUP],
    servedWith: "Served with vegetables.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "SSC035",
    images: [],
  },
  {
    id: "mi_special_seafood_platter",
    name: "Seafood platter",
    description: "Grilled fish, calamari, octopus, prawns, lobster.",
    categoryId: "cat_special_orders",
    kitchenSection: "seafood",
    basePrice: 45,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [SPECIAL_SIDE_GROUP],
    servedWith: "Served with vegetables.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["fish", "shellfish"],
    isAvailable: true,
    isPopular: true,
    sku: "SFP045",
    images: [],
  },
  {
    id: "mi_special_lobster",
    name: "Lobster",
    description: "Grilled lobster.",
    categoryId: "cat_special_orders",
    kitchenSection: "seafood",
    basePrice: 25,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [SPECIAL_SIDE_GROUP],
    servedWith: "Served with vegetables.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: true,
    sku: "LBR025",
    images: [],
  },
  {
    id: "mi_special_jumbo_prawns",
    name: "Jumbo prawns",
    description: "Grilled jumbo prawns.",
    categoryId: "cat_special_orders",
    kitchenSection: "seafood",
    basePrice: 22,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [SPECIAL_SIDE_GROUP],
    servedWith: "Served with vegetables.",
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "JMP022",
    images: [],
  },

  // PASTA (5 items)
  {
    id: "mi_pasta_spaghetti",
    name: "Spaghetti pasta",
    description: "With tomato sauce.",
    categoryId: "cat_pasta",
    kitchenSection: "continental",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [PASTA_SAUCE_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "SPG010",
    images: [],
  },
  {
    id: "mi_pasta_penne",
    name: "Penne pasta",
    description: "With chicken.",
    categoryId: "cat_pasta",
    kitchenSection: "continental",
    basePrice: 12,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [PASTA_SAUCE_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "PNP012",
    images: [],
  },
  {
    id: "mi_pasta_tagliatelle",
    name: "Tagliatelle pasta",
    description: "With prawns.",
    categoryId: "cat_pasta",
    kitchenSection: "continental",
    basePrice: 14,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [PASTA_SAUCE_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "TGP014",
    images: [],
  },
  {
    id: "mi_pasta_linguine",
    name: "Linguine pasta",
    description: "With choice of tuna or king fish.",
    categoryId: "cat_pasta",
    kitchenSection: "continental",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_linguine_tuna",
        name: "Tuna",
        price: 14,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_linguine_kingfish",
        name: "King fish",
        price: 14,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: true,
    groups: [PASTA_SAUCE_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "fish"],
    isAvailable: true,
    isPopular: false,
    sku: "LGP014",
    images: [],
  },
  {
    id: "mi_pasta_seafood",
    name: "Seafood pasta",
    description: "Mixed seafood; fish, prawns, calamari, octopus.",
    categoryId: "cat_pasta",
    kitchenSection: "continental",
    basePrice: 15,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "complex_combo",
    hasVariants: false,
    hasGroups: true,
    groups: [PASTA_SAUCE_GROUP],
    nightMenu: { isAvailable: false },
    isVeg: false,
    isVegan: false,
    isHalal: true,
    allergens: ["gluten", "dairy", "fish", "shellfish"],
    isAvailable: true,
    isPopular: false,
    sku: "SPF015",
    images: [],
  },
];

async function seed() {
  console.log("🚀 Seeding Part 3 (34 items)...\n");
  const now = new Date();
  const batch = db.batch();
  for (const item of menuItems) {
    const { id, ...data } = item;
    batch.set(db.collection(COLLECTION).doc(id), {
      ...data,
      createdAt: now,
      updatedAt: now,
    });
    console.log(`📝 ${item.name}`);
  }
  await batch.commit();
  console.log(`\n✅ Part 3 complete: ${menuItems.length} items seeded!`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
