/**
 * Beverage Menu Items Seeder - Part 1 (Items 1-30)
 * Iced Tea (4) + Smoothies (5) + Mocktails (4) + Cocktails (2) +
 * Red Wines (3) + White Wines (3) + Vodka (3) + Gin (3) + Tequila (3)
 * Run: npx tsx scripts/seedBeverageItems-part1.ts
 */
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!serviceAccountJson) {
    console.error("❌ FIREBASE_SERVICE_ACCOUNT_JSON not set");
    process.exit(1);
  }
  const sa = JSON.parse(serviceAccountJson);
  initializeApp({ credential: cert(sa), projectId: sa.project_id });
}

const db = getFirestore();
const COLLECTION = "foodMenuItems";

const beverageItems = [
  // ===========================================================================
  // ICED TEA & COFFEE (4 items) - cat_iced_tea_coffee
  // ===========================================================================
  {
    id: "item_itc001",
    name: "Lemon Iced Tea",
    description: "Black tea, lemon juice, sugar syrup",
    images: [],
    categoryId: "cat_iced_tea_coffee",
    kitchenSection: "bar",
    basePrice: 4,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "ITC001",
  },
  {
    id: "item_itc002",
    name: "Hibiscus Iced Tea",
    description: "Hibiscus tea, lime slice, sugar syrup",
    images: [],
    categoryId: "cat_iced_tea_coffee",
    kitchenSection: "bar",
    basePrice: 4,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "ITC002",
  },
  {
    id: "item_itc003",
    name: "Cinnamon & Cardamom Iced Tea",
    description: "Cinnamon tea, cardamom tea, sugar syrup",
    images: [],
    categoryId: "cat_iced_tea_coffee",
    kitchenSection: "bar",
    basePrice: 4,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "ITC003",
  },
  {
    id: "item_itc004",
    name: "Iced Coffee",
    description: "Coffee, milk, syrup, ice",
    images: [],
    categoryId: "cat_iced_tea_coffee",
    kitchenSection: "bar",
    basePrice: 4,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "ITC004",
  },

  // ===========================================================================
  // SMOOTHIES (5 items) - cat_smoothies
  // ===========================================================================
  {
    id: "item_smo001",
    name: "Sultan Favourite",
    description:
      "Mango, pineapple, milk, passion fruit, apple, strawberry syrup",
    images: [],
    categoryId: "cat_smoothies",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "SMO001",
  },
  {
    id: "item_smo002",
    name: "Golden Harvest",
    description: "Apple, mango, milk, simple syrup",
    images: [],
    categoryId: "cat_smoothies",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "SMO002",
  },
  {
    id: "item_smo003",
    name: "Apple Banana",
    description: "Apple, banana, milk",
    images: [],
    categoryId: "cat_smoothies",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: false,
    sku: "SMO003",
  },
  {
    id: "item_smo004",
    name: "Sultan Mixed",
    description: "Cashew nut, banana, avocado, milk, syrup",
    images: [],
    categoryId: "cat_smoothies",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy", "nuts"],
    isAvailable: true,
    isPopular: true,
    sku: "SMO004",
  },
  {
    id: "item_smo005",
    name: "Healthy Chocolate",
    description: "Dates, cocoa, cardamom powder, chocolate powder, milk",
    images: [],
    categoryId: "cat_smoothies",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: true,
    allergens: ["dairy"],
    isAvailable: true,
    isPopular: true,
    sku: "SMO005",
  },

  // ===========================================================================
  // MOCKTAILS (4 items) - cat_mocktails
  // ===========================================================================
  {
    id: "item_moc001",
    name: "Virgin Mojito",
    description: "Mint, lime wedges, sugar syrup, Sprite",
    images: [],
    categoryId: "cat_mocktails",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "MOC001",
  },
  {
    id: "item_moc002",
    name: "Virgin Colada",
    description: "Pineapple wedges, coconut cream, sugar syrup",
    images: [],
    categoryId: "cat_mocktails",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "MOC002",
  },
  {
    id: "item_moc003",
    name: "Mango Mule",
    description: "Mango purée, lime juice, ginger soda",
    images: [],
    categoryId: "cat_mocktails",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MOC003",
  },
  {
    id: "item_moc004",
    name: "Cucumber Lime Cooler",
    description: "Cucumber, lime juice, honey, soda water",
    images: [],
    categoryId: "cat_mocktails",
    kitchenSection: "bar",
    basePrice: 6,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: true,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "MOC004",
  },

  // ===========================================================================
  // COCKTAILS (2 items) - cat_cocktails
  // ===========================================================================
  {
    id: "item_coc001",
    name: "Mojito",
    description: "White rum, mint, lime wedges, sugar, soda water",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC001",
  },
  {
    id: "item_coc002",
    name: "Margarita",
    description: "Tequila, lime juice, triple sec",
    images: [],
    categoryId: "cat_cocktails",
    kitchenSection: "bar",
    basePrice: 10,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "simple",
    hasVariants: false,
    variants: [],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "COC002",
  },

  // ===========================================================================
  // RED WINES (3 items) - cat_red_wines - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_rwi001",
    name: "Gato Negro Pinot Noir",
    description: "Chilean red wine with notes of cherry and raspberry",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi001_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi001_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "RWI001",
  },
  {
    id: "item_rwi002",
    name: "Dodoma Dry",
    description: "Tanzanian red wine, dry and medium-bodied",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi002_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi002_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "RWI002",
  },
  {
    id: "item_rwi003",
    name: "Star of Africa Cabernet Sauvignon",
    description: "South African red wine with bold flavors",
    images: [],
    categoryId: "cat_red_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_rwi003_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_rwi003_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "RWI003",
  },

  // ===========================================================================
  // WHITE WINES (3 items) - cat_white_wines - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_wwi001",
    name: "Star of Africa Sauvignon Blanc",
    description: "Crisp and refreshing South African white wine",
    images: [],
    categoryId: "cat_white_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_wwi001_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_wwi001_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "WWI001",
  },
  {
    id: "item_wwi002",
    name: "Star of Africa Chenin",
    description: "Smooth white wine with fruity notes",
    images: [],
    categoryId: "cat_white_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_wwi002_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_wwi002_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: false,
    sku: "WWI002",
  },
  {
    id: "item_wwi003",
    name: "Gato Chardonnay",
    description: "Chilean white wine with buttery finish",
    images: [],
    categoryId: "cat_white_wines",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_wwi003_glass",
        name: "Glass",
        price: 8,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_wwi003_bottle",
        name: "Bottle",
        price: 36,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: false,
    isHalal: false,
    allergens: ["sulfites"],
    isAvailable: true,
    isPopular: true,
    sku: "WWI003",
  },

  // ===========================================================================
  // VODKA (3 items) - cat_vodka - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_vod001",
    name: "Grey Goose",
    description: "Premium French vodka, smooth and refined",
    images: [],
    categoryId: "cat_vodka",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_vod001_shot",
        name: "Shot",
        price: 5,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_vod001_bottle",
        name: "Bottle",
        price: 140,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "VOD001",
  },
  {
    id: "item_vod002",
    name: "Smirnoff Red",
    description: "Classic vodka with clean taste",
    images: [],
    categoryId: "cat_vodka",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_vod002_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_vod002_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "VOD002",
  },
  {
    id: "item_vod003",
    name: "Absolut Blue",
    description: "Swedish vodka with rich and smooth character",
    images: [],
    categoryId: "cat_vodka",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_vod003_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_vod003_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "VOD003",
  },

  // ===========================================================================
  // GIN (3 items) - cat_gin - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_gin001",
    name: "Hendrick's",
    description: "Premium gin infused with cucumber and rose",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin001_shot",
        name: "Shot",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin001_bottle",
        name: "Bottle",
        price: 160,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "GIN001",
  },
  {
    id: "item_gin002",
    name: "Tanqueray",
    description: "Classic London dry gin with juniper notes",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin002_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin002_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "GIN002",
  },
  {
    id: "item_gin003",
    name: "Bombay Sapphire",
    description: "Premium gin with botanical blend",
    images: [],
    categoryId: "cat_gin",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_gin003_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_gin003_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "GIN003",
  },

  // ===========================================================================
  // TEQUILA (3 items) - cat_tequila - VARIANT_BASED
  // ===========================================================================
  {
    id: "item_teq001",
    name: "Patrón Silver",
    description: "Premium silver tequila, smooth and refined",
    images: [],
    categoryId: "cat_tequila",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_teq001_shot",
        name: "Shot",
        price: 6,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_teq001_bottle",
        name: "Bottle",
        price: 160,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "TEQ001",
  },
  {
    id: "item_teq002",
    name: "Jose Cuervo Silver",
    description: "Classic silver tequila with crisp flavor",
    images: [],
    categoryId: "cat_tequila",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_teq002_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_teq002_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: true,
    sku: "TEQ002",
  },
  {
    id: "item_teq003",
    name: "Jose Cuervo Gold",
    description: "Golden tequila with smooth, aged character",
    images: [],
    categoryId: "cat_tequila",
    kitchenSection: "bar",
    basePrice: null,
    currency: "USD",
    taxPercent: 15,
    discount: { isActive: false, type: "percentage", value: 0 },
    itemType: "variant_based",
    hasVariants: true,
    variants: [
      {
        id: "var_teq003_shot",
        name: "Shot",
        price: 4,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "var_teq003_bottle",
        name: "Bottle",
        price: 110,
        isAvailable: true,
        sortOrder: 2,
      },
    ],
    hasGroups: false,
    groups: [],
    servedWith: "",
    nightMenu: { isAvailable: false, nightItemId: "", overridePrice: null },
    isVeg: true,
    isVegan: true,
    isHalal: false,
    allergens: [],
    isAvailable: true,
    isPopular: false,
    sku: "TEQ003",
  },
];

// Seed function
async function seedBeverageItems() {
  console.log("\n🍹 Seeding Beverage Items - Part 1 (30 items)...\n");
  const batch = db.batch();
  const now = new Date();

  for (const item of beverageItems) {
    const { id, ...data } = item;
    const docRef = db.collection(COLLECTION).doc(id);
    batch.set(docRef, { ...data, createdAt: now, updatedAt: now });
    console.log(`📝 ${item.name} (${item.sku})`);
  }

  await batch.commit();
  console.log(`\n✅ Seeded ${beverageItems.length} beverage items!\n`);
}

seedBeverageItems()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  });
